import { MarketItem, LeaderboardUser } from "../types";

export const MARKET_ITEMS: MarketItem[] = [
  {
    id: "item_super_streak",
    name: "Khiên Bảo Vệ Streak 24h",
    category: "boost",
    price: 100,
    icon: "🛡️",
    description: "Tự động kích hoạt giữ chuỗi học tập nếu bạn bận rộn bỏ lỡ 1 ngày.",
    rarity: "rare",
  },
  {
    id: "item_double_bread",
    name: "Nhân Đôi Bánh Mì (24 Giờ)",
    category: "boost",
    price: 200,
    icon: "⚡",
    description: "Nhận gấp đôi số lượng Bánh Mì thưởng khi làm quiz và bài tập.",
    rarity: "epic",
  },
  {
    id: "item_badge_master",
    name: "Huy Hiệu Bậc Thầy Từ Vựng",
    category: "badge",
    price: 150,
    icon: "🏅",
    description: "Huy hiệu vinh danh học sinh chuyên cần vượt mốc 100 từ vựng.",
    rarity: "common",
  },
  {
    id: "item_badge_champion",
    name: "Huy Hiệu Chiến Thần Đấu Trường",
    category: "badge",
    price: 300,
    icon: "⚔️",
    description: "Huy hiệu siêu ngầu dành cho chiến binh bất bại tại Arena 1v1.",
    rarity: "epic",
  },
  {
    id: "item_avatar_crown",
    name: "Khung Avatar Vương Miện Quán Quân",
    category: "avatar",
    price: 500,
    icon: "👑",
    description: "Khung avatar lấp lánh hoàng gia thể hiện vị thế top 1 bảng xếp hạng.",
    rarity: "legendary",
  },
  {
    id: "item_avatar_cyber",
    name: "Khung Avatar Cyberpunk Neon",
    category: "avatar",
    price: 450,
    icon: "💠",
    description: "Hiệu ứng viền phát sáng Neon Cyan & Magenta tương lai đậm chất game thủ.",
    rarity: "rare",
  },
  {
    id: "item_notebook",
    name: "Sổ Tay Từ Vựng BreadTrans Cute",
    category: "gift",
    price: 1200,
    icon: "📔",
    description: "Quà hiện vật sổ tay ghi chú bìa cứng gửi bưu điện về tận nhà.",
    rarity: "epic",
  },
  {
    id: "item_tea_voucher",
    name: "Voucher Trà Sữa Phúc Long 30K",
    category: "gift",
    price: 2000,
    icon: "🧋",
    description: "Đổi mã E-Voucher thưởng đồ uống thơm ngon xua tan căng thẳng.",
    rarity: "legendary",
  },
  {
    id: "item_capybara_plush",
    name: "Gấu Bông Capybara Bánh Mì",
    category: "gift",
    price: 4500,
    icon: "🧸",
    description: "Gấu bông Capybara kẹp bánh mì siêu mịn độc quyền BreadTrans.",
    rarity: "legendary",
  },
  {
    id: "item_thermos_bottle",
    name: "Bình Giữ Nhiệt BreadTrans 500ml",
    category: "gift",
    price: 3500,
    icon: "🍶",
    description: "Bình giữ nhiệt inox 304 cao cấp giữ nóng lạnh suốt 12 tiếng.",
    rarity: "epic",
  },
];

export const MOCK_LEADERBOARD: LeaderboardUser[] = [
  { id: "u1", name: "Minh Anh (Junior)", avatar: "🦊", breads: 1850, streak: 28, rank: 1 },
  { id: "u2", name: "Bảo Nam", avatar: "🐼", breads: 1420, streak: 21, rank: 2 },
  { id: "u3", name: "Gia Hân", avatar: "🐰", breads: 1240, streak: 19, rank: 3 },
  { id: "u4", name: "Tuấn Kiệt", avatar: "🦁", breads: 950, streak: 14, rank: 4 },
  { id: "u5", name: "Phương Linh", avatar: "🐱", breads: 830, streak: 12, rank: 5 },
  { id: "u6", name: "Quang Huy", avatar: "🐯", breads: 670, streak: 9, rank: 6 },
];
