"use client";

import Link from "next/link";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { ArrowRight, CheckCircle2, ClipboardCheck, Loader2, RotateCcw } from "lucide-react";
import { diagnosticService, DiagnosticResult } from "@/lib/api/services/diagnostic.service";

export default function DiagnosticPage() {
  const { data: assessment, isLoading, isError } = useQuery({ queryKey: ["diagnostic-current"], queryFn: diagnosticService.getCurrent });
  const [started, setStarted] = useState(false);
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Record<string, number>>({});
  const submit = useMutation({ mutationFn: () => diagnosticService.submit(assessment!.id, answers) });

  if (isLoading) return <div className="flex min-h-80 items-center justify-center"><Loader2 className="animate-spin text-violet-600" size={34} /></div>;
  if (isError || !assessment) return <div className="mx-auto max-w-xl rounded-2xl border border-rose-100 bg-rose-50 p-6 text-center text-sm font-bold text-rose-700">Chưa thể tải bài kiểm tra đầu vào. Vui lòng thử lại sau.</div>;
  const current = assessment.questions[step];
  const result: DiagnosticResult | undefined = submit.data;
  const reset = () => { setStarted(false); setStep(0); setAnswers({}); submit.reset(); };

  if (result) return <div className="mx-auto max-w-5xl space-y-6 pb-16"><section className="rounded-[2rem] border border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-sky-50 p-8 shadow-card sm:p-10"><span className="inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-xs font-extrabold text-emerald-700"><CheckCircle2 size={15} /> Đã lưu kết quả</span><h1 className="mt-4 text-3xl font-black text-slate-900">Bạn đang ở mức {result.level}</h1><p className="mt-2 text-slate-600">Bạn đúng {result.correctCount}/{result.totalCount} câu ({result.percentage}%). Kết quả này đã được lưu vào lịch sử luyện tập.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/practice" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-extrabold text-white hover:bg-violet-700">Bắt đầu luyện tập <ArrowRight size={17} /></Link><button type="button" onClick={reset} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 text-sm font-extrabold text-slate-700 hover:bg-slate-50"><RotateCcw size={17} /> Làm lại</button></div></section></div>;

  if (!started) return <div className="mx-auto max-w-5xl space-y-6 pb-16"><section className="rounded-[2rem] border border-violet-100 bg-gradient-to-br from-violet-50 via-white to-sky-100 p-8 shadow-card sm:p-10"><span className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-white px-3 py-1 text-xs font-extrabold text-violet-700"><ClipboardCheck size={15} /> Dữ liệu thật</span><h1 className="mt-4 text-3xl font-black text-slate-900 sm:text-4xl">{assessment.title}</h1><p className="mt-3 max-w-2xl leading-6 text-slate-600">{assessment.description || "Trả lời các câu hỏi ngắn để nhận điểm bắt đầu phù hợp."}</p><p className="mt-4 text-sm font-bold text-violet-700">{assessment.questions.length} câu hỏi • Kết quả được lưu vào hồ sơ học tập</p><button type="button" onClick={() => setStarted(true)} className="mt-6 inline-flex min-h-12 items-center gap-2 rounded-xl bg-violet-600 px-5 text-sm font-extrabold text-white hover:bg-violet-700">Bắt đầu kiểm tra <ArrowRight size={18} /></button></section></div>;

  return <div className="mx-auto max-w-4xl space-y-6 pb-16"><header className="rounded-2xl border border-slate-200 bg-white p-5 shadow-soft"><div className="flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-violet-700">Kiểm tra đầu vào</p><h1 className="mt-1 text-xl font-black text-slate-900">Câu {step + 1}/{assessment.questions.length}</h1></div><span className="rounded-xl bg-violet-50 px-3 py-2 text-xs font-extrabold text-violet-700">{current.skill}</span></div></header><section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-card sm:p-9"><h2 className="text-xl font-black leading-8 text-slate-900">{current.question}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{current.options.map((option, index) => <button key={option} type="button" onClick={() => setAnswers((old) => ({ ...old, [current.id]: index }))} aria-pressed={answers[current.id] === index} className={`min-h-16 rounded-2xl border-2 px-5 text-left text-sm font-bold ${answers[current.id] === index ? "border-violet-500 bg-violet-50" : "border-slate-200 hover:border-violet-200"}`}><span className="mr-3 text-violet-600">{String.fromCharCode(65 + index)}.</span>{option}</button>)}</div><div className="mt-8 flex justify-between"><button type="button" onClick={() => setStep((value) => Math.max(0, value - 1))} disabled={!step} className="min-h-11 px-4 text-sm font-bold text-slate-500 disabled:opacity-40">Câu trước</button><button type="button" disabled={answers[current.id] === undefined || submit.isPending} onClick={() => step === assessment.questions.length - 1 ? submit.mutate() : setStep((value) => value + 1)} className="min-h-11 rounded-xl bg-violet-600 px-5 text-sm font-extrabold text-white disabled:opacity-50">{submit.isPending ? "Đang chấm..." : step === assessment.questions.length - 1 ? "Xem kết quả" : "Câu tiếp"}</button></div>{submit.isError && <p className="mt-4 text-sm font-bold text-rose-600">Không thể nộp bài. Vui lòng thử lại.</p>}</section></div>;
}
